version: '3'

services:
  mysql1234:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: go_users
  
  task:
    build: service
    restart: always
    ports:
      - 33097:7777
    depends_on:
      - mysql1234

