version: '2.3'

services:
  task:
    build: service
    restart: always

    mem_limit: 256M
    memswap_limit: 256M
    pids_limit: 512

    ulimits:
      nofile:
        soft: 1024
        hard: 1024

    ports:
      - 42771:31337
