version: '2.3'

services:
  task:
    build: service
    restart: always

    mem_limit: 512M
    memswap_limit: 512M
    pids_limit: 1024

    ulimits:
      nofile:
        soft: 1536
        hard: 1536

    ports:
      - 40518:31337
