version: '2.3'

services:
  task:
    container_name: captcha_server
    image: captcha_server_image
    build: service
    restart: always
    ports:
      - 33040:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
