version: '2.3'

services:
  task:
    container_name: arbacoin_bank
    image: image_arbacoin_bank
    build: service
    restart: always
    ports:
      - 33069:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
