version: '2.3'

services:
  task:
    container_name: arbacoi_wallet
    image: image_arbacoin_wallet_image
    build: service
    restart: always
    ports:
      - 33052:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
