version: '2.3'

services:
  task:
    container_name: remote_auth_server
    image: remote_auth_server_image
    build: service
    restart: always
    ports:
      - 33051:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
